Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: logs
  LogFileName: blog
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Passport: 123456
  Host: 127.0.0.1
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: luo
  Issuer: blog
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxxx@163.com
  Password: xxxxxxxx
  IsSSL: true
  From: xxxx@163.com
  To:
    - xxxx@163.com